### ISSUE TITLE
Please add instructions to use your image with pre existing disk

### ISSUE THREAD

**Issue by rjalexa** [k44sh/ruTorrent#11]
I am very grateful for your work but would need a little help.

I have a large external disk attached to my Raspberry seedbox and I have mounted it on a /4TBHDD mountpoint.

I would really need some help to figure out which environment variables I should set in the docker compose file to map my existing seedbox files. Here are the details:

If I list the files on /4TBHDD I would for example see:
```
bob@rutorrent:/4TBHDD $ ls -la
total 1068
drwxrwx---  6 www-data bob    4096 Jan 17  2024 .
drwxr-xr-x 19 root     root   4096 Dec  4 16:00 ..
drwxrwx--- 14 www-data bob    4096 Dec  2 22:10 download
drwxrwx---  2 www-data bob   16384 Jan 23  2020 lost+found
drwxrwx---  2 www-data bob  565248 Dec  3 10:31 .session
drwxrwx---  2 www-data bob  499712 Jan 17  2024 .session_backup
```
and of course inside the .session directory I have stuff like:
```
-rw-r--r-- 1 www-data bob    3511 Jan 18  2024 FFEEBBDB0158D59667462619CA3D6F381E9CA395.torrent
-rw-r--r-- 1 bob      bob     235 Dec  3 10:18 FFEEBBDB0158D59667462619CA3D6F381E9CA395.torrent.libtorrent_resume
-rw-r--r-- 1 bob      bob     905 Dec  3 10:18 FFEEBBDB0158D59667462619CA3D6F381E9CA395.torrent.rtorrent
-rw-r--r-- 1 bob      bob      55 Dec  3 10:18 rtorrent.dht_cache
-rw-r--r-- 1 bob      bob       0 Dec  3 10:18 rtorrent.input_history
-r--r--r-- 1 bob      bob      17 Dec  3 10:31 rtorrent.lock
```
while the /4TBHDD/download directory has a folder structure based on types of contents:
```
bob@rutorrent:/4TBHDD $ ls -l download/
total 284
drwxrwx---  44 bob bob   4096 May 30  2024 audio
drwxrwx---   2 bob bob   4096 May 30  2024 autodl
drwxr-xr-x   2 bob bob   4096 Jan 16  2024 complete
drwxrwx--- 226 bob bob 139264 Aug  6 08:45 ebooks
drwxrwx---  77 bob bob   4096 Dec  2 19:30 mac
drwxrwx--- 103 bob bob  94208 Oct 15 10:47 movies
drwxrwx---  97 bob bob  12288 May 30  2024 music
drwxrwxrwx   2 bob bob   4096 Jan 30  2024 temp
drwxrwx---  25 bob bob   4096 Nov 11 18:05 tv
drwxrwx---  34 bob bob   4096 Dec 24  2023 videos
drwxrwx---   3 bob bob   4096 Dec 24  2020 web
drwxrwx---   3 bob bob   4096 Jul 18 21:30 win 
```

Thank you for any help I really hope to be able to use your image and resume my seeding.

**Comment by k44sh** [comment]
HI @rjalexa 

Maybe `device: "/4TBHDD/download/complete"` for the device part and `- data:/data/downloads:rw` for the container part.
Also, there is no default download temp folder.

```yaml
services:
  ### https://github.com/k44sh/rutorrent
  rutorrent:
    image: k44sh/rutorrent
    container_name: rutorrent
    hostname: rutorrent
    restart: always
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    volumes:
      - config:/config:rw
      - data:/data/downloads:rw
      - passwd:/passwd:rw
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    env_file:
      - .env
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./config"
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data"
  passwd:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/4TBHDD/download/complete"
```
