### ISSUE TITLE
Error while attempting to convert service.rutorrent.ports.target to appropriate type: "" is not a valid integer

### ISSUE THREAD

**Issue by ahaghgoo** [k44sh/rutorrent#3]
Hi, 

Thanks for addressing the file management with this fork.  I'm still having trouble starting up the service though.  Here's what I get when I try to run "docker-compose up -d":

``
WARNING: The RT_DHT_PORT variable is not set. Defaulting to a blank string.
``
``
ERROR: Error while attempting to convert service.rutorrent.ports.target to appropriate type: "" is not a valid integer
``

Here's what my compose.yml file looks like: 

```

version: "3.8"

services:
  ### https://github.com/k44sh/rutorrent
  rutorrent:
    image: k44sh/rutorrent
    container_name: rutorrent
    hostname: rutorrent
    restart: always
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    volumes:
      - /share/ZFS530_DATA/.qpkg/container-station/docker/volumes/rTorrent/config:/config:rw
      - /share/ZFS530_DATA/.qpkg/container-station/docker/volumes/rTorrent/data:/data:rw
      - /share/ZFS530_DATA/.qpkg/container-station/docker/volumes/rTorrent/passwd:/passwd:rw
      - "/share/ZFS20_DATA/Multimedia/Torrents/rTorrent/Downloads:/Downloads"
      - "/share/ZFS20_DATA/Multimedia/Torrents/rTorrent/[Watched]:/Watched"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    env_file:
      - .env
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./config"
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data"
  passwd:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./passwd"
```
